services:

  app:
    container_name: app_afdnp
    build:
      context: .
      dockerfile: dockerfile.app
    volumes:
      - ./app:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
    - "13001:3000"
    # command: sh -c "npm install --force && npm run build && npm run start"
    command: sh -c "npm install && npm run start"
    environment:
      - NODE_ENV=production
    networks:
      - afdnp_default
volumes:
  afdnp:

networks:
  afdnp_default:
    driver: bridge